// Compatibility constants generated from shared/compat.yaml.
//
// DO NOT EDIT. This file is generated by `tools/ct_ci.py generate` and
// verified in CI. Change shared/compat.yaml and regenerate; a hand edit
// will fail the generated-files-are-current gate.
//
// shared/compat.yaml is the single source of truth for sidecar tiers,
// engine data-safety state, and export portability. This module exists
// so Node-runtime shipped scripts can read those values without a YAML
// dependency.


export const TIERS: Array<[string, [number, number] | null, [number, number] | null, number, string]> = [
  ['v2.4-read', [2, 4], [2, 5], 8, 'dormant'],
  ['v2.5-full', [2, 5], null, 14, 'full'],
];

export const FULL_TIER_TOOLS = 14;
export const READ_TIER_TOOLS = 8;

export const SOURCE_REF_SHAPE = '^librarian-[0-9a-f]{32}$';
export const EVIDENCE_TABLE = 'librarian_evidence';
export const ENGINE_PINNED_VERSION = '7.1.0';
export const ENGINE_SAFE = false;

export const REQUIRED_TABLES: string[] = [
  'llm_wiki_entries',
  'librarian_evidence',
  'chunks',
  'documents',
  'curated_proposals',
  'curated_proposal_items',
];

export const COMPAT_SOURCE = "shared/compat.yaml";
