"""Render shared/compat.yaml into a stdlib-only Python constants module.

Shipped scripts may not depend on a YAML parser (CONTRIBUTING rule 4), and a
hand-rolled mini-YAML loader is a trap whose edge cases would surface as a
broken doctor on a user's machine. So the compatibility matrix is compiled,
here in CI, into a plain Python module that ships alongside the scripts. CI
regenerates and diffs it on every run, so it cannot drift (spec §3.1, §5.3).
"""
from __future__ import annotations

import re
from pathlib import Path

import yaml

import ct_ci_manifest

HEADER = '''"""Compatibility constants generated from shared/compat.yaml.

DO NOT EDIT. This file is generated by `tools/ct_ci.py generate` and verified
in CI. Change shared/compat.yaml and regenerate; a hand edit will fail the
generated-files-are-current gate.

shared/compat.yaml is the single source of truth for sidecar tiers, engine
data-safety state, and export portability. This module exists so stdlib-only
shipped scripts can read those values without a YAML dependency.
"""
'''

HEADER_TS = '''// Compatibility constants generated from shared/compat.yaml.
//
// DO NOT EDIT. This file is generated by `tools/ct_ci.py generate` and
// verified in CI. Change shared/compat.yaml and regenerate; a hand edit
// will fail the generated-files-are-current gate.
//
// shared/compat.yaml is the single source of truth for sidecar tiers,
// engine data-safety state, and export portability. This module exists
// so Node-runtime shipped scripts can read those values without a YAML
// dependency.
'''

_BOUND_RE = re.compile(r"(>=|<)(\d+)\.(\d+)")


def _bounds(expression):
    """Parse a range like '>=2.4,<2.5' into ((2, 4), (2, 5))."""
    low, high = None, None
    for operator, major, minor in _BOUND_RE.findall(expression or ""):
        pair = (int(major), int(minor))
        if operator == ">=":
            low = pair
        else:
            high = pair
    return low, high


def render(compat):
    """Return the full text of a _compat_generated.py for this matrix."""
    root = compat["compat"]
    tiers = []
    for name in sorted(root["tiers"]):
        tier = root["tiers"][name]
        low, high = _bounds(tier.get("sidecar"))
        tiers.append((name, low, high, tier["tools"], tier["write_path"]))

    read_tools = next(t[3] for t in tiers if t[4] == "dormant")
    full_tools = next(t[3] for t in tiers if t[4] == "full")

    unsafe = [
        state
        for state in root["engine"]["states"].values()
        if not state.get("safe", True)
    ]
    pinned = unsafe[0]["pinned_version"] if unsafe else ""
    safety = root["engine"]["data_safety"]

    lines = [HEADER, "", "TIERS = ("]
    for name, low, high, tools, write_path in tiers:
        lines.append(f"    ({name!r}, {low!r}, {high!r}, {tools!r}, {write_path!r}),")
    lines += [
        ")",
        "",
        f"READ_TIER_TOOLS = {read_tools!r}",
        f"FULL_TIER_TOOLS = {full_tools!r}",
        "",
        f"SOURCE_REF_SHAPE = {safety['source_ref_shape']!r}",
        f"EVIDENCE_TABLE = {safety['evidence_table']!r}",
        f"ENGINE_PINNED_VERSION = {pinned!r}",
        f"ENGINE_SAFE = {not unsafe!r}",
        "",
        "REQUIRED_TABLES = (",
    ]
    for table in root["portability"]["required_tables"]:
        lines.append(f"    {table!r},")
    lines += [
        ")",
        "",
        'COMPAT_SOURCE = "shared/compat.yaml"',
        "",
    ]
    return "\n".join(lines)


def render_ts(compat):
    """Return the full text of a _compat_generated.ts for this matrix.

    Structurally identical to render(): same tier names, version triples,
    tool counts, and evidence table name. Drift between the two outputs is
    a CI gate, so both render from the same parsed compat.yaml.
    """
    root = compat["compat"]
    tiers = []
    for name in sorted(root["tiers"]):
        tier = root["tiers"][name]
        low, high = _bounds(tier.get("sidecar"))
        tiers.append((name, low, high, tier["tools"], tier["write_path"]))

    read_tools = next(t[3] for t in tiers if t[4] == "dormant")
    full_tools = next(t[3] for t in tiers if t[4] == "full")

    unsafe = [
        state
        for state in root["engine"]["states"].values()
        if not state.get("safe", True)
    ]
    pinned = unsafe[0]["pinned_version"] if unsafe else ""
    safety = root["engine"]["data_safety"]

    # TS uses tuple/array literals and null, not Python's None.
    def render_tier(name, low, high, tools, write_path):
        low_str = "[" + ", ".join(str(x) for x in low) + "]" if low else "null"
        high_str = "[" + ", ".join(str(x) for x in high) + "]" if high else "null"
        return f"  [{name!r}, {low_str}, {high_str}, {tools}, {write_path!r}],"

    lines = [
        HEADER_TS,
        "",
        "export const TIERS: Array<[string, [number, number] | null, [number, number] | null, number, string]> = [",
    ]
    for tier in tiers:
        lines.append(render_tier(*tier))
    lines += [
        "];",
        "",
        f"export const FULL_TIER_TOOLS = {full_tools};",
        f"export const READ_TIER_TOOLS = {read_tools};",
        "",
        f"export const SOURCE_REF_SHAPE = {safety['source_ref_shape']!r};",
        f"export const EVIDENCE_TABLE = {safety['evidence_table']!r};",
        f"export const ENGINE_PINNED_VERSION = {pinned!r};",
        f"export const ENGINE_SAFE = {str(not unsafe).lower()};",
        "",
        "export const REQUIRED_TABLES: string[] = [",
    ]
    for table in root["portability"]["required_tables"]:
        lines.append(f"  {table!r},")
    lines += [
        "];",
        "",
        'export const COMPAT_SOURCE = "shared/compat.yaml";',
        "",
    ]
    return "\n".join(lines)


def _compat(repo_root):
    with open(Path(repo_root) / "shared" / "compat.yaml", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def targets(repo_root):
    """Every generated-file path, for implemented Python integrations."""
    paths = []
    for _id, directory, data in ct_ci_manifest.discover_manifests(repo_root):
        if data.get("status") == "implemented" and data.get("language") == "python":
            paths.append(directory / "scripts" / "_compat_generated.py")
    return paths


def ts_targets(repo_root):
    """Every generated-file path, for implemented Node/TypeScript integrations."""
    paths = []
    for _id, directory, data in ct_ci_manifest.discover_manifests(repo_root):
        if data.get("status") == "implemented" and data.get("language") == "node":
            paths.append(directory / "scripts" / "_compat_generated.ts")
    return paths


def write_all(repo_root):
    """Regenerate every target. Returns the paths written."""
    compat = _compat(repo_root)
    py_text = render(compat)
    ts_text = render_ts(compat)
    written = []
    for path in targets(repo_root):
        path.write_text(py_text, encoding="utf-8")
        written.append(path)
    for path in ts_targets(repo_root):
        path.write_text(ts_text, encoding="utf-8")
        written.append(path)
    return written


def check_current(repo_root):
    """Return a stale-file report; empty list means everything is current."""
    compat = _compat(repo_root)
    py_text = render(compat)
    ts_text = render_ts(compat)
    stale = []
    for path in targets(repo_root):
        if not path.exists():
            stale.append(f"{path}: missing — run `python tools/ct_ci.py generate`")
        elif path.read_text(encoding="utf-8") != py_text:
            stale.append(
                f"{path}: stale — shared/compat.yaml changed; "
                "run `python tools/ct_ci.py generate` and commit the result"
            )
    for path in ts_targets(repo_root):
        if not path.exists():
            stale.append(f"{path}: missing — run `python tools/ct_ci.py generate`")
        elif path.read_text(encoding="utf-8") != ts_text:
            stale.append(
                f"{path}: stale — shared/compat.yaml changed; "
                "run `python tools/ct_ci.py generate` and commit the result"
            )
    return stale
