/**
 * test_ct_doctor.ts — fixture-driven tests for the OpenCode doctor.
 *
 * No live sidecar is spawned except where noted (the mcpToolsList tests use
 * a mock `curated-thoughts-mcp` shim on a temp PATH, mirroring the Hermes
 * suite's approach). Registration fixtures build a fake XDG_CONFIG_HOME so
 * the doctor's global-config reads are hermetic.
 */

import { chmodSync, mkdirSync, mkdtempSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { pathToFileURL } from 'node:url';
import { afterAll, describe, expect, it } from 'vitest';

import {
  FAIL,
  PASS,
  UNKNOWN,
  WARN,
  checkBrainDir,
  checkImportPreflight,
  checkOpencodeRegistration,
  checkSidecarBinary,
  checkSidecarIdentity,
  checkVault,
  exitCodeFor,
  formatText,
  mcpToolsList,
  opencodeConfigPath,
  runChecks,
  type CheckResult,
} from '../scripts/ct_doctor.js';

// --------------------------------------------------------------------------
// fixture helpers
// --------------------------------------------------------------------------

let _dirCounter = 0;

function makeHome(): string {
  _dirCounter += 1;
  const base = join(tmpdir(), `ct-doctor-test-${process.pid}-${_dirCounter}`);
  rmSync(base, { recursive: true, force: true });
  mkdirSync(base, { recursive: true });
  return base;
}

function cleanupHome(base: string): void {
  try {
    chmodSync(base, 0o700);
  } catch {
    // best effort
  }
  rmSync(base, { recursive: true, force: true });
}

interface RegistrationFixture {
  home: string;
  env: NodeJS.ProcessEnv;
  configPath: string;
  loaderPath: string;
  skillsDir: string;
}

function makeRegistrationFixture(
  opts: {
    configText?: string | null;
    loaderText?: string | null;
    payloadEntry?: string | null;
    skills?: string[];
  } = {},
): RegistrationFixture {
  const home = makeHome();
  const configDir = join(home, '.config', 'opencode');
  const pluginsDir = join(configDir, 'plugins');
  const skillsDir = join(configDir, 'skills');
  mkdirSync(pluginsDir, { recursive: true });
  mkdirSync(skillsDir, { recursive: true });
  const configPath = join(configDir, 'opencode.json');
  const loaderPath = join(pluginsDir, 'curated-thoughts.js');

  const payloadDir = join(home, 'payload');
  if (opts.payloadEntry !== null) {
    mkdirSync(join(payloadDir, 'lib', 'src'), { recursive: true });
    writeFileSync(join(payloadDir, 'lib', 'src', 'index.js'), 'export {};\n');
  }

  if (opts.configText !== null) {
    writeFileSync(configPath, opts.configText ?? '{}\n');
  }
  if (opts.loaderText !== null) {
    const target = opts.payloadEntry ?? payloadDir;
    writeFileSync(
      loaderPath,
      opts.loaderText ??
        `// Generated by curated-thoughts install.sh — do not edit.\n// Payload: ${target}  (reinstall to move it)\nexport { CuratedThoughts } from ${JSON.stringify(pathToFileURL(join(target, 'lib', 'src', 'index.js')).href)};\n`,
    );
  }
  for (const name of opts.skills ?? [
    'curated-thoughts-usage',
    'curated-thoughts-ops',
    'curated-thoughts-sidecar',
  ]) {
    mkdirSync(join(skillsDir, name), { recursive: true });
    writeFileSync(join(skillsDir, name, 'SKILL.md'), `---\nname: ${name}\ndescription: test\n---\n`);
  }

  return {
    home,
    env: { XDG_CONFIG_HOME: join(home, '.config') } as NodeJS.ProcessEnv,
    configPath,
    loaderPath,
    skillsDir,
  };
}

function byName(results: CheckResult[], name: string): CheckResult {
  const r = results.find((x) => x.name === name);
  expect(r, `check ${name} missing`).toBeDefined();
  return r!;
}

// --------------------------------------------------------------------------
// check 1/2: sidecar binary + identity
// --------------------------------------------------------------------------

describe('checkSidecarBinary', () => {
  it('reports FAIL only when no binary exists anywhere; bundled fallback counts', () => {
    const home = makeHome();
    try {
      // Blank PATH and a HOME with no platform install locations. The
      // platform candidates (/usr/bin, /usr/local/bin, ...) are constants,
      // so the FAIL branch is only reachable on machines without the
      // sidecar — assert whichever branch the host supports, honestly.
      const env = {
        PATH: '',
        HOME: home,
        USERPROFILE: home,
        LOCALAPPDATA: '',
        PROGRAMFILES: '',
      } as NodeJS.ProcessEnv;
      const r = checkSidecarBinary(null, env);
      if (r.status === FAIL) {
        expect(r.hint).toContain('Searched:');
      } else {
        // Found in a fixed platform location (e.g. /usr/bin on a dev box
        // with the sidecar installed) — via the bundled-candidate fallback.
        expect(r.status).toBe(PASS);
        expect(r.detail).toContain('via bundled');
      }
    } finally {
      cleanupHome(home);
    }
  });

  it('passes when the binary is on the fixture PATH', () => {
    const home = makeHome();
    try {
      const bin = join(home, 'bin');
      mkdirSync(bin);
      writeFileSync(join(bin, 'curated-thoughts-mcp'), '#!/bin/sh\n');
      chmodSync(join(bin, 'curated-thoughts-mcp'), 0o755);
      const env = { PATH: bin } as NodeJS.ProcessEnv;
      const r = checkSidecarBinary(null, env);
      expect(r.status).toBe(PASS);
      expect(r.detail).toContain('via PATH');
    } finally {
      cleanupHome(home);
    }
  });
});

describe('checkSidecarIdentity', () => {
  it('warns (skipped) when there is no binary', () => {
    const r = checkSidecarIdentity(null, null);
    expect(r.status).toBe(WARN);
  });

  it('warns on a dev build shadowing the installed sidecar', () => {
    const r = checkSidecarIdentity('/usr/local/bin/curated-thoughts-mcp', '/home/u/ct/target/debug/curated-thoughts-mcp');
    expect(r.status).toBe(WARN);
    expect(r.detail).toContain('development build');
  });

  it('passes for an installed location', () => {
    const r = checkSidecarIdentity('/usr/bin/curated-thoughts-mcp', '/usr/bin/curated-thoughts-mcp');
    expect(r.status).toBe(PASS);
  });
});

// --------------------------------------------------------------------------
// check 3: MCP probe over stdio (mock sidecar, no live binary required)
// --------------------------------------------------------------------------

describe('mcpToolsList', () => {
  it('answers tools/list from a mock sidecar', () => {
    const home = makeHome();
    try {
      const bin = join(home, 'bin');
      mkdirSync(bin);
      const shim = join(bin, 'curated-thoughts-mcp');
      // The sidecar is spawned as `curated-thoughts-mcp --mcp`, so the mock
      // is a tiny sh script that execs a sibling node script — no `env node`
      // shebang, which /bin/sh's env rejects with option-style arguments.
      const shimJs = join(bin, 'ct-mock-sidecar.mjs');
      writeFileSync(
        shimJs,
        `let buf='';\n` +
          `process.stdin.on('data',(d)=>{buf+=d;\n` +
          `  for(;;){const i=buf.indexOf('\\n');if(i<0)break;const line=buf.slice(0,i);buf=buf.slice(i+1);\n` +
          `    if(!line.trim())continue;let m;try{m=JSON.parse(line)}catch{continue}\n` +
          `    if(m.method==='initialize'){process.stdout.write(JSON.stringify({jsonrpc:'2.0',id:m.id,result:{protocolVersion:'2024-11-05',capabilities:{},serverInfo:{name:'ct',version:'2.12.0'}}})+'\\n')}\n` +
          `    else if(m.method==='tools/list'){process.stdout.write(JSON.stringify({jsonrpc:'2.0',id:m.id,result:{tools:Array.from({length:14},(_,k)=>({name:'t'+k}))}})+'\\n')}\n` +
          `  }});\n`,
      );
      writeFileSync(shim, `#!/bin/sh\nexec "${process.execPath}" "${shimJs}"\n`);
      chmodSync(shim, 0o755);
      const res = mcpToolsList(shim, 10, { PATH: bin } as NodeJS.ProcessEnv);
      expect(res.error).toBeNull();
      expect(res.toolNames).toHaveLength(14);
      expect(res.serverVersion).toBe('2.12.0');
    } finally {
      cleanupHome(home);
    }
  });

  it('reports an error for a crashing sidecar', () => {
    const home = makeHome();
    try {
      const bin = join(home, 'bin');
      mkdirSync(bin);
      const shim = join(bin, 'curated-thoughts-mcp');
      writeFileSync(shim, '#!/bin/sh\nexit 3\n');
      chmodSync(shim, 0o755);
      const res = mcpToolsList(shim, 10, { PATH: bin } as NodeJS.ProcessEnv);
      expect(res.error).not.toBeNull();
      expect(res.toolNames).toBeNull();
    } finally {
      cleanupHome(home);
    }
  });

  it('reports an error for a missing binary', () => {
    const res = mcpToolsList('/nonexistent/curated-thoughts-mcp', 1, {} as NodeJS.ProcessEnv);
    expect(res.error).not.toBeNull();
  });
});

// --------------------------------------------------------------------------
// checks 4/5: brain dir + vault
// --------------------------------------------------------------------------

describe('checkBrainDir + checkVault', () => {
  it('fails on a missing brain dir', () => {
    const home = makeHome();
    try {
      const env = { CURATED_BRAIN_DIR: join(home, 'brain') } as NodeJS.ProcessEnv;
      const r = checkBrainDir(undefined, env);
      expect(r.status).toBe(FAIL);
    } finally {
      cleanupHome(home);
    }
  });

  it('passes with db + config present', () => {
    const home = makeHome();
    try {
      const brain = join(home, 'brain');
      mkdirSync(brain);
      writeFileSync(join(brain, 'brain.db'), '');
      writeFileSync(join(brain, 'config.json'), JSON.stringify({ vault_path: home }));
      const env = { CURATED_BRAIN_DIR: brain } as NodeJS.ProcessEnv;
      expect(checkBrainDir(undefined, env).status).toBe(PASS);
      expect(checkVault(undefined, env).status).toBe(PASS);
    } finally {
      cleanupHome(home);
    }
  });

  it('warns when the brain dir lacks db and config', () => {
    const home = makeHome();
    try {
      const brain = join(home, 'brain');
      mkdirSync(brain);
      const env = { CURATED_BRAIN_DIR: brain } as NodeJS.ProcessEnv;
      const r = checkBrainDir(undefined, env);
      expect(r.status).toBe(WARN);
      expect(r.detail).toContain('brain.db, config.json');
    } finally {
      cleanupHome(home);
    }
  });

  it('fails when vault_path is absent from a readable config', () => {
    const home = makeHome();
    try {
      const brain = join(home, 'brain');
      mkdirSync(brain);
      writeFileSync(join(brain, 'brain.db'), '');
      writeFileSync(join(brain, 'config.json'), '{}');
      const env = { CURATED_BRAIN_DIR: brain } as NodeJS.ProcessEnv;
      const r = checkVault(undefined, env);
      expect(r.status).toBe(FAIL);
    } finally {
      cleanupHome(home);
    }
  });

  it('fails on an imported brain whose vault path does not exist', () => {
    const home = makeHome();
    try {
      const brain = join(home, 'brain');
      mkdirSync(brain);
      writeFileSync(join(brain, 'config.json'), JSON.stringify({ vault_path: '/nonexistent/vault' }));
      const env = { CURATED_BRAIN_DIR: brain } as NodeJS.ProcessEnv;
      const r = checkVault(undefined, env);
      expect(r.status).toBe(FAIL);
      expect(r.hint).toContain('imported');
    } finally {
      cleanupHome(home);
    }
  });
});

// --------------------------------------------------------------------------
// check 7: OpenCode registration — the three evidence pieces
// --------------------------------------------------------------------------

describe('checkOpencodeRegistration', () => {
  it('passes when all three pieces of evidence are in place', () => {
    const fx = makeRegistrationFixture({
      configText: JSON.stringify({
        $schema: 'https://opencode.ai/config.json',
        mcp: { 'curated-thoughts': { type: 'local', command: ['curated-thoughts-mcp', '--mcp'], enabled: true, environment: {} } },
      }),
    });
    try {
      const r = checkOpencodeRegistration(fx.env);
      expect(r.status).toBe(PASS);
      expect(r.detail).toContain('mcp["curated-thoughts"]');
      expect(r.detail).toContain('loader file');
      expect(r.detail).toContain('all three skills');
    } finally {
      cleanupHome(fx.home);
    }
  });

  it('reports UNKNOWN — not a FAIL — when the entry is absent from the global config', () => {
    const fx = makeRegistrationFixture({ configText: '{}' });
    try {
      const r = checkOpencodeRegistration(fx.env);
      expect(r.status).toBe(UNKNOWN);
      expect(r.detail).toContain('not found in');
      expect(r.detail).toContain('also merges project and managed config');
      expect(r.hint).toBeTruthy();
    } finally {
      cleanupHome(fx.home);
    }
  });

  it('reports UNKNOWN when the global config file does not exist at all', () => {
    const fx = makeRegistrationFixture({ configText: null });
    try {
      const r = checkOpencodeRegistration(fx.env);
      expect(r.status).toBe(UNKNOWN);
      expect(r.detail).toContain('not found in');
    } finally {
      cleanupHome(fx.home);
    }
  });

  it('fails when the global config is unparseable (JSONC-tolerant parse still fails)', () => {
    const fx = makeRegistrationFixture({ configText: '{ this is not json ]' });
    try {
      const r = checkOpencodeRegistration(fx.env);
      expect(r.status).toBe(FAIL);
      expect(r.detail).toContain('unreadable');
      expect(r.detail).toContain('could not parse');
    } finally {
      cleanupHome(fx.home);
    }
  });

  it('tolerates JSONC comments and trailing commas when reading the config', () => {
    const fx = makeRegistrationFixture({
      configText:
        '{\n'
        + '  // my comments survive\n'
        + '  "$schema": "https://opencode.ai/config.json",\n'
        + '  "mcp": {\n'
        + '    "curated-thoughts": { "type": "local", "command": ["curated-thoughts-mcp", "--mcp"], "enabled": true, },\n'
        + '  },\n'
        + '}',
    });
    try {
      const r = checkOpencodeRegistration(fx.env);
      expect(r.status).toBe(PASS);
    } finally {
      cleanupHome(fx.home);
    }
  });

  it('prefers opencode.jsonc when both exist', () => {
    const fx = makeRegistrationFixture({ configText: '{ "mcp": {} }' });
    try {
      const jsonc = join(join(fx.home, '.config', 'opencode'), 'opencode.jsonc');
      writeFileSync(
        jsonc,
        JSON.stringify({ mcp: { 'curated-thoughts': { type: 'local', command: ['curated-thoughts-mcp', '--mcp'], enabled: true } } }),
      );
      expect(opencodeConfigPath(fx.env)).toBe(jsonc);
      const r = checkOpencodeRegistration(fx.env);
      expect(r.status).toBe(PASS);
      expect(r.detail).toContain('opencode.jsonc');
    } finally {
      cleanupHome(fx.home);
    }
  });

  it('fails when a mcp entry has the wrong shape', () => {
    const fx = makeRegistrationFixture({
      configText: JSON.stringify({ mcp: { 'curated-thoughts': { type: 'remote', url: 'https://x' } } }),
    });
    try {
      const r = checkOpencodeRegistration(fx.env);
      expect(r.status).toBe(FAIL);
      expect(r.detail).toContain('unexpected shape');
    } finally {
      cleanupHome(fx.home);
    }
  });

  it('warns when the entry is explicitly disabled (preserved disablement)', () => {
    const fx = makeRegistrationFixture({
      configText: JSON.stringify({
        mcp: { 'curated-thoughts': { type: 'local', command: ['curated-thoughts-mcp', '--mcp'], enabled: false } },
      }),
    });
    try {
      const r = checkOpencodeRegistration(fx.env);
      expect(r.status).toBe(WARN);
      expect(r.detail).toContain('disabled');
    } finally {
      cleanupHome(fx.home);
    }
  });

  it('FAILs with a reinstall hint when the loader points at a missing payload', () => {
    const fx = makeRegistrationFixture({ payloadEntry: null });
    try {
      const r = checkOpencodeRegistration(fx.env);
      expect(r.status).toBe(FAIL);
      expect(r.detail).toContain('missing payload');
      expect(r.hint).toContain('Re-install');
    } finally {
      cleanupHome(fx.home);
    }
  });

  it('passes the loader piece when only the loader file exists (mcp entry still UNKNOWN)', () => {
    const fx = makeRegistrationFixture({ configText: '{}' });
    try {
      const r = checkOpencodeRegistration(fx.env);
      expect(r.status).toBe(UNKNOWN);
      expect(r.detail).toContain('loader file present');
    } finally {
      cleanupHome(fx.home);
    }
  });

  it('warns when the mcp entry is fine but skills are missing', () => {
    const fx = makeRegistrationFixture({
      configText: JSON.stringify({
        mcp: { 'curated-thoughts': { type: 'local', command: ['curated-thoughts-mcp', '--mcp'], enabled: true } },
      }),
      skills: [],
    });
    try {
      const r = checkOpencodeRegistration(fx.env);
      expect(r.status).toBe(WARN);
      expect(r.detail).toContain('skills missing');
    } finally {
      cleanupHome(fx.home);
    }
  });

  it('fails when the loader file is a directory (unreadable as a loader)', () => {
    const fx = makeRegistrationFixture({ loaderText: null });
    try {
      mkdirSync(fx.loaderPath, { recursive: true });
      const r = checkOpencodeRegistration(fx.env);
      expect(r.status).toBe(FAIL);
      expect(r.detail).toContain('not a regular file');
    } finally {
      cleanupHome(fx.home);
    }
  });

  it('fails when a loader exists but belongs to another install', () => {
    const fx = makeRegistrationFixture({ loaderText: 'export { Something } from "other";\n' });
    try {
      const r = checkOpencodeRegistration(fx.env);
      // Not ours: the doctor cannot call it broken, but it cannot count as
      // evidence either; the mcp entry decides the overall verdict.
      expect([PASS, WARN, UNKNOWN]).toContain(r.status);
      if (r.status === PASS || r.status === WARN) {
        expect(r.detail).toContain('does not re-export');
      }
    } finally {
      cleanupHome(fx.home);
    }
  });
});

// --------------------------------------------------------------------------
// check 8: import pre-flight wiring
// --------------------------------------------------------------------------

describe('checkImportPreflight', () => {
  it('warns when the brain database is missing', () => {
    const home = makeHome();
    try {
      const env = { CURATED_BRAIN_DIR: join(home, 'nope') } as NodeJS.ProcessEnv;
      const r = checkImportPreflight({ env });
      expect(r.status).toBe(WARN);
      expect(r.detail).toContain('could not census');
    } finally {
      cleanupHome(home);
    }
  });
});

// --------------------------------------------------------------------------
// exit codes + JSON output (Step 5.8)
// --------------------------------------------------------------------------

describe('exit codes and formatting', () => {
  it('exit 0 all PASS, 1 any FAIL, 2 WARN-only', () => {
    expect(exitCodeFor([{ name: 'a', status: PASS, detail: '' }])).toBe(0);
    expect(exitCodeFor([{ name: 'a', status: WARN, detail: '' }])).toBe(2);
    expect(
      exitCodeFor([
        { name: 'a', status: PASS, detail: '' },
        { name: 'b', status: WARN, detail: '' },
      ]),
    ).toBe(2);
    expect(exitCodeFor([{ name: 'a', status: FAIL, detail: '' }])).toBe(1);
    expect(
      exitCodeFor([
        { name: 'a', status: FAIL, detail: '' },
        { name: 'b', status: WARN, detail: '' },
      ]),
    ).toBe(1);
  });

  it('UNKNOWN alone is not a failure (exit 0)', () => {
    expect(exitCodeFor([{ name: 'a', status: UNKNOWN, detail: '' }])).toBe(0);
  });

  it('formatText counts UNKNOWN separately', () => {
    const text = formatText([
      { name: 'a', status: PASS, detail: 'ok' },
      { name: 'b', status: UNKNOWN, detail: 'unknown' },
    ]);
    expect(text).toContain('0 FAIL, 0 WARN, 1 UNKNOWN, 1 PASS');
    expect(text).toContain('[UNKNOWN] b');
  });
});

describe('clean-room JSON output (Step 5.8)', () => {
  it('runs all 9 checks and emits parseable JSON with an unreachable brain', () => {
    const home = makeHome();
    try {
      const env: NodeJS.ProcessEnv = {
        PATH: join(home, 'empty-bin'),
        CURATED_BRAIN_DIR: join(home, 'no-brain'),
        XDG_CONFIG_HOME: join(home, '.config'),
      };
      const results = runChecks({ env });
      expect(results).toHaveLength(9);
      expect(results.map((r) => r.name)).toEqual([
        'sidecar-binary',
        'sidecar-identity',
        'sidecar-mcp',
        'brain-dir',
        'vault',
        'embedding-backend',
        'opencode-registration',
        'import-preflight',
        'version-compat',
      ]);
      // Every check resolved to a verdict — none crashed.
      for (const r of results) {
        expect([PASS, WARN, FAIL, UNKNOWN]).toContain(r.status);
      }
      // JSON serialization survives (the --json contract).
      const json = JSON.stringify({ exit_code: exitCodeFor(results), checks: results });
      expect(() => JSON.parse(json)).not.toThrow();
    } finally {
      cleanupHome(home);
    }
  });
});

// --------------------------------------------------------------------------
// CLI smoke: the compiled doctor runs from lib/ and exits 0/1/2
// --------------------------------------------------------------------------

describe('CLI', () => {
  const libDoctor = join(import.meta.dirname ?? '.', '..', 'lib', 'scripts', 'ct_doctor.js');

  it('--json emits valid JSON and a 0/1/2 exit code', () => {
    const home = makeHome();
    try {
      const res = spawnSync(
        process.execPath,
        [libDoctor, 'check', '--json'],
        {
          encoding: 'utf8',
          env: {
            ...process.env,
            XDG_CONFIG_HOME: join(home, '.config'),
            CURATED_BRAIN_DIR: join(home, 'brain'),
          },
        },
      );
      expect(res.error ?? null).toBeNull();
      expect([0, 1, 2]).toContain(res.status);
      const parsed = JSON.parse(res.stdout);
      expect(parsed.checks).toHaveLength(9);
      expect(parsed.exit_code).toBe(res.status);
    } finally {
      cleanupHome(home);
    }
  });

  it('prints help for an unknown subcommand without crashing', () => {
    const res = spawnSync(process.execPath, [libDoctor, 'bogus'], { encoding: 'utf8' });
    expect(res.error ?? null).toBeNull();
    expect(res.status).toBe(0);
    expect(res.stdout).toContain('Usage');
  });
});
